version: 0.9.{build}.0
branches:
  only:
  - master
skip_tags: true
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: BuildAllConfigurations.proj
  verbosity: normal
after_build:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER

    cd '.nuget'

    ./nuget.exe pack '..\SQLite.CodeFirst\SQLite.CodeFirst.csproj' -Properties -Symbols -OutputDirectory '..\SQLite.CodeFirst\bin'
artifacts:
- path: SQLite.CodeFirst\bin
  name: Assemblies
- path: SQLite.CodeFirst\bin\*.nupkg
  name: NuPkg
deploy:
- provider: NuGet
  api_key:
    secure: QmbFnerlfTAFUZpnaPgVDywMH4fF8rVakefmqvhu3qm9SpuDlLGB9S4HwtdE3Nep
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: https://www.nuget.org/packages/SQLite.CodeFirst/
  auth_token:
    secure: e3cqaFy9PzI9TAdZJBIDy97Bfbwa7j0EXe2yw7Ev9aJXK0Q+3mnULqb1VU4P7BWR
  artifact: Assemblies,NuPkg
  draft: true
  on:
    branch: master
notifications:
- provider: Webhook
  url: https://zapier.com/hooks/catch/b3cbz0/
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false